
import { GoogleGenAI, Type } from "@google/genai";
import { Task } from "../types";

// Always use process.env.API_KEY directly to initialize the Gemini client
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Interface representing the structure of a sub-task generated by the AI.
 */
export interface ExpandedSubTask {
  title: string;
  description: string;
  daysDuration: number;
}

/**
 * Breaks down a macro task into smaller, actionable sub-tasks using Gemini AI.
 * Uses gemini-3-pro-preview for advanced reasoning and breakdown logic.
 */
export const expandMacroTask = async (macroTitle: string, currentContext: string): Promise<ExpandedSubTask[]> => {
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-preview',
    contents: `
      Act as a senior event project manager. Break down the macro task "${macroTitle}" for the "Nambikkai Launch Event" into 5-8 granular, actionable sub-tasks.
      Event Details: ${currentContext}.
      The output must be a JSON array of sub-tasks with title, description, and suggested duration in days.
    `,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            title: { 
              type: Type.STRING,
              description: "Short title of the sub-task"
            },
            description: { 
              type: Type.STRING,
              description: "Detailed explanation of the sub-task requirements"
            },
            daysDuration: { 
              type: Type.NUMBER,
              description: "The number of days estimated to complete this specific sub-task"
            }
          },
          required: ["title", "description", "daysDuration"]
        }
      }
    }
  });

  try {
    // The .text property directly returns the generated string output.
    const jsonStr = response.text || "[]";
    return JSON.parse(jsonStr.trim());
  } catch (e) {
    console.error("Failed to parse AI response into sub-tasks", e);
    return [];
  }
};

/**
 * Analyzes the project's task list and provides expert insights using gemini-3-flash-preview.
 */
export const getProjectInsights = async (tasks: Task[]): Promise<string> => {
  const summary = tasks.map(t => `${t.title} (${t.status})`).join(', ');
  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: `
      Review the following event project schedule and provide 3-5 concise, high-impact bullet points on risks or optimizations.
      Tasks: ${summary}
    `
  });
  
  // Use the .text property to retrieve the analysis from the Gemini model.
  return response.text || "No insights available at this time.";
};
